spring:
  profiles: default
  application:
    name: springboot-aws-starter
  datasource:
    initialization-mode: always
    schema: classpath:/scripts/schema.sql
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect  
    hibernate:
      ddl-auto: none
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
      
cloud:
  aws:
    credentials:
      instanceProfile: false
    region:
      auto: false
      static: 'us-west-1'
    stack:
      auto: false
            
# Make the application available at http://localhost:8080
# These are default settings, but we add them for clarity.
server:
  port: 8080
  servlet:
    context-path: /springboot-aws-starter
  
logging:
  level:
    org.springframework: INFO
    com.example.aws: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: logs/springboot-aws-starter.log

---

spring:
  profiles: aws
  application:
    name: springboot-aws-starter
  datasource:
    initialization-mode: never
    schema: classpath:/scripts/schema.sql
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
      
cloud:
  aws:
    credentials:
      instanceProfile: true
      useDefaultAwsCredentialsChain: true
    region:
      auto: true
    stack:
      auto: false
 
server:
  port: 8080
  servlet:
    context-path: /springboot-aws-starter
  
logging:
  level:
    org.springframework: INFO
    com.example.aws: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: logs/springboot-aws-starter.log

